AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: AWS SAM Nested Applications

Resources:
    StackDynamodb:
        Type: AWS::Serverless::Application
        Properties:
            Location: apps/dynamodb/template.yaml

    StackRestApi:
        Type: AWS::Serverless::Application
        Properties:
            Location: apps/rest-api/template.yaml
            Parameters:
                TableCategoriesArn: !GetAtt StackDynamodb.Outputs.TableCategoriesArn
                TableCategoriesName: !GetAtt StackDynamodb.Outputs.TableCategoriesName

Outputs:
    ServerlessRestApi:
        Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
        Value: !GetAtt StackRestApi.Outputs.ServerlessRestApiUrl
